CREATE DATABASE phpcrud CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE albums (
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200),
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp DEFAULT CURRENT_TIMESTAMP
)